# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/6"

  # https://www.vagrantup.com/docs/synced-folders/rsync.html
  config.vm.synced_folder "../", "/vagrant", type: "rsync",
    rsync__exclude: "data/"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
        sudo yum -y install git gcc glibc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel

        git clone https://github.com/yyuu/pyenv.git ~/.pyenv
        git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
        echo 'export PATH="$HOME/.pyenv/shims:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> ~/.bashrc
        echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

        source ~/.bashrc

        CONFIGURE_OPTS=--enable-shared pyenv install -f 3.6.4

        pyenv shell 3.6.4
        pip install --upgrade pip
        pip install -r /vagrant/requirements.txt
        pip install pyinstaller
  SHELL
end
